version: '3.8'
services:
  kickstart-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: com.example/spring-boot-kickstart
    ports:
      - 8080:8080
    environment:
      management.endpoints.web.exposure.include: env
    restart: on-failure